name: Semantic Release on Merge to Main

on:
  push:
    branches:
      - main  # Trigger workflow on pushes to the main branch

jobs:
  semantic-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Install Semantic Release
        run: npm install -g semantic-release

      - name: Run Semantic Release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # GitHub token for releasing
        run: |
          npm run semantic-release