name: Deploy Theme to Shopify on merge to develop branch

on:
  push:
    branches:
      - '**'  # Runs on every branch
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1
          bundler: 'latest'

      - name: Install Shopify CLI
        run: |
          npm install -g @shopify/cli @shopify/theme

      - name: Set theme tag
        id: theme_tag
        run: |
          echo "tag=${{ github.ref_name }}-${{ github.sha }}" >> $GITHUB_ENV

      - name: Deploy to Shopify
        env:
          SHOPIFY_FLAG_STORE: https://671345-8e.myshopify.com
          SHOPIFY_CLI_THEME_TOKEN: ${{ secrets.SHOPIFY_API_TOKEN }}
        run: |
          shopify theme push --unpublished --theme="${{ env.tag }}"
