name: Deploy Theme to Shopify

on:
  push:
    branches:
      - '**'  # Runs on every branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 'lts/*'  # Ensure this matches your project's node version

      - name: Install dependencies
        run: npm install

      - name: Deploy to Shopify
        env:
          SHOPIFY_STORE: https://671345-8e.myshopify.com # Store URL e.g., your-store.myshopify.com
          SHOPIFY_PASSWORD: password  # Admin API password for theme deployment
        run: |
          shopify login --store=https://671345-8e.myshopify.com --password=password 
          
          shopify theme push --environment=production
