name: Deploy Theme to Shopify

on:
  push:
    branches:
      - '**'  # Runs on every branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 'lts/*'  # Ensure this matches your project's node version

      - name: Install dependencies
        run: npm install

      - name: Install Shopify CLI
        run: |
          npm install -g @shopify/cli @shopify/theme

      - name: Deploy to Shopify
        env:
          SHOPIFY_STORE: https://671345-8e.myshopify.com
          SHOPIFY_API_TOKEN: ${{ secrets.SHOPIFY_API_TOKEN }}
        run: |
          shopify theme push --unpublished --password=$SHOPIFY_API_TOKEN --store=$SHOPIFY_STORE --theme="First CI theme 1"
